[
	["Andrew Brower"],
	["Andrew Warren"],
	["Anna Zubek"],
	["Anton Chichvarkhin"],
	["Antónia Monteiro"],
	["Carlos Peña"],
	["Chris Wheat"],
	["Dan Janzen"],
	["Daniel Rubinoff"],
	["David Lees"],
	["Debra Murray"],
	["Elena Ortiz"],
	["Elisabet Weingartner"],
	["Emily Hornett"],
	["Evelyn Sanchez"],
	["Felix Sperling"],
	["Franziska Bauer"],
	["GenBank"],
	["Heike Witthauer"],
	["Irena Slamova"],
	["Ivonne Garzon-Orduna"],
	["Jadranka Rota"],
	["Jenni Mäkynen"],
	["Julien Leneveu"],
	["Karina Lucas"],
	["Kayce Casner"],
	["Kwaku Aduse-Poku"],
	["Margarita Beltrán"],
	["Marianne Elias Lab"],
	["Marko Mutanen"],
	["Michael Braby"],
	["Michel,F"],
	["Naomi Pierce"],
	["Niklas Wahlberg"],
	["Pável Matos"],
	["Rachel Anderson"],
	["Rayner Núñez"],
	["Regier"],
	["Reza Zahiri"],
	["Robin Van Velzen"],
	["Sean Mullen"],
	["Shaun Walton"],
	["Takashi Yagi"],
	["Thomas Simonsen"],
	["Tohru Katoh"],
	["Ullasa Kodandaramaiah"],
]
