[
	["Andrew Brower"],
	["Carlos Peña"],
	["Chris Müller"],
	["Christian Schulze"],
	["Dave A. Edge"],
	["Harry Pavulaan"],
	["J. Grados, C. Peña & J. Böttger"],
	["Martin Steinbauer"],
	["Naomi Pierce"],
	["Niklas Wahlberg"],
	["Niklas Wahlberg & Carlos Peña"],
	["Tobias Malm"],
	["Torben B. Larsen"],
]
