[
	["Andrew Brower"],
	["Andrew Warren"],
	["Anna Zubek"],
	["Anton Chichvarkhin"],
	["Antónia Monteiro"],
	["Carlos Peña"],
	["Daniel Rubinoff"],
	["Debra Murray"],
	["Elena Ortiz"],
	["Elisabet Weingartner"],
	["Felix Sperling"],
	["Franziska Bauer"],
	["Heike Witthauer"],
	["Irena Slamova"],
	["Ivonne Garzon-Orduna"],
	["Jadranka Rota"],
	["Jenni Mäkynen"],
	["Julien Leneveu"],
	["Karina Lucas"],
	["Karina Silva"],
	["Kwaku Aduse-Poku"],
	["Margarita Beltrán"],
	["Marko Mutanen"],
	["Michael Braby"],
	["Naomi Pierce"],
	["Niklas Wahlberg"],
	["NULL"],
	["Pável Matos"],
	["Rachel Anderson"],
	["Rayner Núñez"],
	["Ricardo Mallarino"],
	["Takashi Yagi"],
	["Tania Deodati"],
	["Thomas Simonsen"],
	["Tohru Katoh"],
	["Ullasa Kodandaramaiah"],
]
