[
	["?"],
	["AFGHANISTAN"],
	["ALBANIA"],
	["ALGERIA"],
	["ANGOLA"],
	["ANJOUAN"],
	["ARGENTINA"],
	["ARGENTINA?"],
	["ARMENIA"],
	["ASK TOM EMMEL"],
	["AUSTRALIA"],
	["AUSTRIA"],
	["AZERBAIJAN"],
	["BAHAMAS"],
	["BANGLADESH"],
	["Belgium"],
	["BELIZE"],
	["Bioko"],
	["BOLIVIA"],
	["BORNEO"],
	["BORNEO, SABAH"],
	["BRASIL"],
	["BRAZIL"],
	["BULGARIA"],
	["Butterfly house supplier"],
	["CAMEROON"],
	["Cameroun"],
	["CANADA"],
	["Canada?"],
	["CENTRAL AFRICAN REPUBLIC"],
	["CHILE"],
	["CHINA"],
	["COLOMBIA"],
	["CONGO"],
	["COSTA RICA"],
	["Croatia"],
	["CUBA"],
	["CYPRUS"],
	["CZECH REPUBLIC"],
	["DENMARK"],
	["DOMINICA"],
	["DOMINICAN REPUBLIC"],
	["DRC"],
	["E DRC"],
	["E. DRC"],
	["EAST TIMOR"],
	["ECUADOR"],
	["EGYPT"],
	["EL SALVADOR"],
	["EQUATORIAL GUINEA"],
	["Espagne"],
	["ESTONIA"],
	["ETHIOPIA"],
	["FINLAND"],
	["FRANCE"],
	["FRENCH GUIANA"],
	["GABON"],
	["Georgia"],
	["GERMANY"],
	["GHANA"],
	["GRANDE COMORO"],
	["Grande Comoros"],
	["GREECE"],
	["Greenhouse stock Stanford Univ."],
	["GREENLAND"],
	["GUADELOUPE"],
	["GUATEMALA"],
	["GUINEA"],
	["Guinea Bissau"],
	["GUYANA"],
	["Honduras"],
	["Hong Kong"],
	["HUNGARY"],
	["INDIA"],
	["INDONESIA"],
	["IRAN"],
	["ISRAEL"],
	["ITALY"],
	["JAMAICA"],
	["JAPAN"],
	["KAKSTAN"],
	["Kamchatka pen - la"],
	["KAZAKHSTAN"],
	["KENYA"],
	["KENYA?"],
	["KYRGYZSTAN"],
	["LAB POPULATION"],
	["LAOS"],
	["LEBANON"],
	["Lesotho"],
	["LIBERIA"],
	["London Pupae Supplies"],
	["Macedonia"],
	["MADAGASCAR"],
	["MADEIRA"],
	["MALAWI"],
	["MALAYSIA"],
	["MALTA"],
	["MARQUESAS"],
	["MARTINIQUE"],
	["MAURITIUS S"],
	["MAYOTTE"],
	["MEXICO"],
	["MOHELI W"],
	["MONGOLIA"],
	["MONTENEGRO"],
	["MOROCCO"],
	["Mozambique"],
	["NEPAL"],
	["NEW CALEDONIA"],
	["NEW GEORGIA"],
	["NEW ZEALAND"],
	["NICARAGUA"],
	["NIGERIA"],
	["NIGERIA (E)"],
	["NIGERIA (N)"],
	["NIGERIA (W)"],
	["NORTH KOREA"],
	["NORWAY"],
	["PAKISTAN"],
	["PANAMA"],
	["PAPUA NEW GUINEA"],
	["PEMBA ISLAND"],
	["PERU"],
	["PHILIPPINES"],
	["PNG"],
	["PORTUGAL"],
	["REUNION ISLAND"],
	["REUNION NE"],
	["ROMANIA"],
	["RUSSIA"],
	["RWANDA"],
	["S. AFRICA"],
	["SIERRA LEONE"],
	["Slovakia"],
	["SLOVENIA"],
	["Solomon Islands"],
	["Solomons Island"],
	["SOUTH AFRICA"],
	["South Korea"],
	["SPAIN"],
	["Spain?"],
	["SRI LANKA"],
	["Stratford Butterfly Farm, UK"],
	["SUMATRA"],
	["SURINAM"],
	["SWEDEN"],
	["SWITZERLAND"],
	["TAIWAN"],
	["TAJIKISTAN"],
	["TANZANIA"],
	["THAILAND"],
	["Tian-Shan"],
	["TOGO"],
	["TUNISIA"],
	["TURKEY"],
	["TURKMENIA"],
	["UABEKISTAN"],
	["UGANDA"],
	["UKRAINE"],
	["UNITED KINGDOM"],
	["UNITED STATES OF AMERICA"],
	["USA"],
	["UZBEKISTAN"],
	["VENEZUELA"],
	["VIETNAM"],
	["YEMEN"],
	["Yugoslavia"],
	["ZAMBIA"],
	["ZIMBABWE"],
]
