[
	["A. Atkins"],
	["A. Coati"],
	["A. D. Warren"],
	["A. Fernando"],
	["A. G. Belik"],
	["A. Grkovich leg."],
	["A. Guanilo"],
	["A. Jasinski"],
	["A. Kapkaev"],
	["A. Karbalaye leg."],
	["A. Müller"],
	["A. N. Streltzov & P. E. Osipov"],
	["A. Pérez-Asso"],
	["A. R. M. Silva"],
	["A. Sourakov"],
	["A. Timchenko"],
	["A. V. L. Freitas"],
	["A. Wakeham-Dawson leg."],
	["A. Y. Kawahara leg."],
	["ABRI"],
	["ABRI Coll"],
	["Adam M. Cotton"],
	["Alain Olivier"],
	["ALEKSEENKO A"],
	["Alex Grkovich"],
	["Alexei Belik"],
	["Alireza Naderi"],
	["Amy Jao"],
	["Anders Angerbjörn"],
	["André Freitas"],
	["Andrei Sourakov"],
	["Andrew B. Martynenko"],
	["Andrew Brower"],
	["Andrew D. Warren"],
	["Andrew Neild"],
	["Andrew Rawlins"],
	["Andriambelo_M."],
	["Andy Warren"],
	["Ang Yao"],
	["Anila Paparisto"],
	["Anton Chichvarkin"],
	["Arturo Ramirez"],
	["Atte Komonen"],
	["B. Calderón"],
	["B. Hager"],
	["B. Holm"],
	["Barb & Calvin Beck"],
	["Barb & Jim Beck"],
	["Barb Beck"],
	["Barbagia"],
	["Belik A. G. & Belik S. A."],
	["Bengt Karlsson"],
	["Benigno Calderon"],
	["Betko B, Cesanek M, Rekelj J"],
	["Bill Gendron"],
	["Bill Overal"],
	["Bob Parsons"],
	["Bouyer coll."],
	["Britta Johansson"],
	["Bruce Walsh"],
	["Butterfly house supplier"],
	["C. Bordelon"],
	["C. Brévignon"],
	["C. E. Giraldo"],
	["C. Kremen"],
	["C. Luckens leg."],
	["C. Rossi"],
	["C. Tello"],
	["C. Wiskin"],
	["Carla Penz"],
	["Carlos Peña"],
	["Carlos Peña & Carol Castillo"],
	["Carol Boggs"],
	["Carol Castillo"],
	["Cata"],
	["Cerny K"],
	["Cesanek M"],
	["Cesaroni"],
	["Chris Jiggins"],
	["Chris Müller"],
	["Chris Schmidt"],
	["Christer Solbreck"],
	["Christer Wiklund"],
	["Christer??"],
	["Christian Brévignon"],
	["Christian Schulze"],
	["Christophe Thébaud"],
	["Coll. A. Neild."],
	["Constantí Stefanescu"],
	["Crispin Guppy"],
	["D. Bonte"],
	["D. Britton"],
	["D. C. Lees"],
	["D. J. Harvey"],
	["D. James (Andy Warren)"],
	["D. Knowles"],
	["D. Lane"],
	["D. McDermott"],
	["D. Moore"],
	["D. Muniz"],
	["D. P. Knoop"],
	["D. Povolny"],
	["Dan Janzen"],
	["Dan Thackaberry"],
	["Dana Ross"],
	["Daniel Janzen"],
	["Danilo B. Ribeiro"],
	["Darrell Kemp"],
	["Dave A. Edge"],
	["David L. Threatful"],
	["David Lees"],
	["David Lohman"],
	["David Wright"],
	["Deane Bowers"],
	["Debra Murray"],
	["Debra Murray coll."],
	["Derek Bridgehouse"],
	["Diehl"],
	["Dietz"],
	["Dmitriy Goshko"],
	["Dolibaina & Carneiro"],
	["Doug Kroon"],
	["Douglas Mullins"],
	["E. Fonseca & E. Oliva"],
	["E. N. Bustos"],
	["E. O. Emery"],
	["E. Pérez"],
	["E. Punta"],
	["Eckweiler"],
	["Elisabet Weingartner"],
	["Emmel_T. C."],
	["Enrique Garcia-Barros"],
	["Erik Thorsell"],
	["Ernest Williams"],
	["ex coll Turlin"],
	["Extraction from Klas"],
	["F. Chang"],
	["F. Molleman"],
	["F. Pérez"],
	["F. Steiner"],
	["F. Vegliante"],
	["Fabrice Caulson"],
	["Felix Sperling"],
	["Freerk Molleman"],
	["G. C. Bozano"],
	["G. Hirschfeld leg."],
	["G. Lamas"],
	["G. Valencia"],
	["G. Vande Weghe"],
	["G. Velastegui"],
	["G. Vignali"],
	["G. Volpe"],
	["G. Waldeck"],
	["G. Wurtz"],
	["Georg Nygren"],
	["George Gibbs"],
	["Gerdo Achtelik"],
	["Giacomazzo"],
	["Gordon F. Pratt"],
	["Goshko D"],
	["Gregory R. Ballmer"],
	["Guangchun Lei"],
	["H. Ebert"],
	["H. F. Greeney"],
	["H. Rojas"],
	["Hajo Gernaat"],
	["Hao Cai Yun"],
	["Hao Cai Yun coll."],
	["Harry Pavulaan"],
	["Harry Pavulaan OR David Wright"],
	["Harry Pavulaan/N Andover"],
	["Harry Pavulaan/Tony Moore"],
	["Heike Witthauer"],
	["Heikki Roininen"],
	["Hron, Cesanek M, Rekelj"],
	["HS Staude"],
	["I. Tuf"],
	["Ian G. Woods"],
	["Ilkka Hanski"],
	["Ilya N. Osipov"],
	["Insects International"],
	["Ismael Aldaz"],
	["Isrrael Gómez"],
	["Ivonin V"],
	["J & F Preston (Andy Warren)"],
	["J Kielland"],
	["J. -P. Kaitila"],
	["J. B. Walsh"],
	["J. Ball"],
	["J. Bizarro"],
	["J. Boettger"],
	["J. C. Makris leg"],
	["J. Dunford"],
	["J. Ek"],
	["J. Engdal leg."],
	["J. Grados & A. Asenjo"],
	["J. Grados, C. Peña & J. Böttger"],
	["J. Grados, J. Boettger, C. Peña"],
	["J. H. Boersma"],
	["J. Hernandez"],
	["J. J. Ramírez"],
	["J. Klir"],
	["J. Laiho"],
	["J. Lay"],
	["J. León-Cortés"],
	["J. M. Maes"],
	["J. Maes"],
	["J. P. Brock"],
	["J. Pateman"],
	["J. Wieringa"],
	["Jaakko Kullberg"],
	["James Kruse"],
	["James Scott"],
	["Janet Sperling"],
	["Janusz Wojtusiak & Tomasz Pyrcz"],
	["Jean Claude Petit"],
	["Jeff Harding"],
	["Jeff Oliver"],
	["Jens Rydell"],
	["Jere Salminen"],
	["Jevgeni Meiken"],
	["Jim Beck"],
	["Jiri & Petr Klir"],
	["Jiri Klir"],
	["John Calhoun"],
	["John Tennent"],
	["Jorge Salazaar"],
	["Juan Grados"],
	["Juan Grados & Angélico Asenjo"],
	["Jukka Jalava"],
	["Julian Bayliss"],
	["Julien Leneveu"],
	["Jun-Ichi Asahi"],
	["JY & LD Miller leg."],
	["K. Davenport leg."],
	["K. Fiedler"],
	["K. Nupponen, J. Junnilainen"],
	["K. Ullasa"],
	["K. Willmott"],
	["K. Willmott & J. Hall"],
	["K. Yeranyan"],
	["Kalle Gotthard, Sören Nylin, Constantí Stefanescu"],
	["Kari Nupponen"],
	["Karl Gotthard, Elisabet Weingartner, Erik Thorsell"],
	["Katy Prudic"],
	["Kauri Mikkola"],
	["Keith R. Willmott"],
	["Keith R. Willmott & Jason P. W. Hall"],
	["Keith R. Willmott & R. Aldaz"],
	["Keith W. Larson"],
	["Ken Davenport"],
	["Kesselring"],
	["Kipnis"],
	["Klas Nyblom"],
	["Klaus Karttunen"],
	["Klir"],
	["Knoop leg."],
	["Kravchuk and Gauristchuk"],
	["Kruger & Saldaitis"],
	["KULESHOV & OLEG TARCHENKOV"],
	["Kuleshov and Tarchenkov"],
	["Kuvandyk vil."],
	["Kwaku Aduse-Poku"],
	["L. Alexander"],
	["L. Arango"],
	["L. Bieber"],
	["L. Dapporto leg."],
	["L. Domozetsni"],
	["L. Filipova"],
	["L. Harris"],
	["L. Lehmann"],
	["Lauri Kaila"],
	["Lemström"],
	["Leonardo Dapporto"],
	["Love Dalen"],
	["Luc Legal"],
	["Lucas Kaminski"],
	["M Stangeland"],
	["M. A. Marín"],
	["M. A. Pigo"],
	["M. Costa"],
	["M. G. Pees"],
	["M. H. Villet"],
	["M. J. Pellinen"],
	["M. Kalabza"],
	["M. L. Munguira & Hernandez"],
	["M. Lucarelli"],
	["M. Mej"],
	["M. Paluch"],
	["M. Pickett"],
	["M. Pinzari"],
	["M. Rowlings Leg."],
	["M. S. Molgaard leg."],
	["M. Stangeland (Andy Warren)"],
	["M. Takahashi leg."],
	["M. Tarrier"],
	["M. U. Prado"],
	["M. Valentini"],
	["M. Wilson"],
	["MacKereth"],
	["Manuel Tafur"],
	["Manuela Pinzari"],
	["Marie Zimmermann"],
	["Mark Cornwall"],
	["Mark Walker"],
	["Marta Vila"],
	["Martin Konvicka"],
	["Martin Steinbauer"],
	["Martin Weimers"],
	["Michael F. Braby"],
	["Michael Leski"],
	["Michael Singer"],
	["Michel"],
	["Michel Tarrier"],
	["Mielke & Carneiro"],
	["Mielke & Casagrande"],
	["Mielke, Maia, & Dolibaina"],
	["Mielke, Maia, Carneiro & Dolibaina"],
	["Mike Leski"],
	["Mike Soukup"],
	["Miller, Miller & Rozyicki"],
	["Minna Miettinen"],
	["MO et al"],
	["MO, ME, VA"],
	["Molgaard leg"],
	["N. Fernández"],
	["N. G. Kondla"],
	["N. Hirai"],
	["N. N."],
	["N. Slitinvov leg."],
	["Naderi"],
	["Naomi Pierce"],
	["Niklas Janz"],
	["Niklas Wahlberg"],
	["Niklas Wahlberg & Andrew Warren"],
	["Niklas Wahlberg & Carlos Peña"],
	["Niklas Wahlberg, Niklas Janz, Sören Nylin"],
	["Nils Ryrholm"],
	["Norbert Kondla"],
	["NOT KNOWN"],
	["O. Mielke"],
	["Onildo João Marini Filho"],
	["Osipov"],
	["Oskar Brattström"],
	["Owen Garvie"],
	["P-O Wickman"],
	["P. Aibar"],
	["P. Beda"],
	["P. Duque"],
	["P. J. C. Russell"],
	["P. Matos"],
	["P. Walwanda"],
	["Pak Chris"],
	["Paul Catling"],
	["Paul Opler"],
	["Paulus"],
	["Peter Goliev"],
	["Peter Russell"],
	["Phil DeVries"],
	["Pierre Boyer"],
	["PN/EE"],
	["R Vorgas"],
	["R. Aldaz"],
	["R. Bischetti"],
	["R. D. Warren"],
	["R. Ducarme"],
	["R. Eastwood"],
	["R. Núñez"],
	["R. Núñez, A. Barro & D. Saladrigas"],
	["R. Rozyoki"],
	["R. van Velzen"],
	["R. Vieira"],
	["Rachel Anderson"],
	["Raharitsimba_T"],
	["Ranaivosolo_Ravomiarana"],
	["Rank"],
	["Razafindraibe_P."],
	["Renato Rogner Ramos"],
	["Renske E Onstein"],
	["Robert Dana"],
	["Rodriguez de Mendoza"],
	["Roger Grund"],
	["Roger Vila"],
	["Ronald Gatrelle"],
	["Ronny Leestmans"],
	["Ross Layberry"],
	["Runar Krogen"],
	["Rusin N."],
	["S Collins"],
	["S. Beretta leg."],
	["S. Beshkov"],
	["S. C. Collins coll ex A. Peyrieras"],
	["S. D. Davkov"],
	["S. Davkov leg."],
	["S. Daykov"],
	["S. Padrón & R. Aldaz"],
	["S. Schröder"],
	["S. Szabolcs"],
	["S. Vashchenko"],
	["S. Walton"],
	["Saara Wahlberg"],
	["Safi & Zaker"],
	["safi et al"],
	["Safian"],
	["Sáfián, Sz. in coll"],
	["Sergei Rudykh"],
	["Shnip A"],
	["Slobodan Davkov"],
	["Sören Nylin"],
	["Sören Nylin, Toomas Tammaru"],
	["Sotnikovo V"],
	["Starzi Kary"],
	["Stéphanie Gallusser"],
	["Steve Collins"],
	["Steve Kohler"],
	["Steve Woodhall"],
	["Strohle"],
	["SY/RV"],
	["Syamsul"],
	["Syamsul Alan"],
	["Syamsul coll."],
	["Szabolcs Sáfián"],
	["T. Bouyer"],
	["T. Ortenburger"],
	["T. Quental"],
	["TEC/IB/MR/PW"],
	["Ted"],
	["Ted Pike"],
	["Tero Piirainen & Martti Kuisma"],
	["Tero Piirainen & Pekka Vantanen"],
	["The Insect Company"],
	["Thomas Schmidt"],
	["Thomas Simonsen"],
	["Tim Davenport"],
	["Tjeerd B. Jongeling"],
	["Tkadlec T"],
	["Tomasz Pyrcz"],
	["Tommi Wahlberg"],
	["Tony Moore"],
	["Tony Nagypal"],
	["Toomas Tammaru"],
	["Torb"],
	["Torben B. Larsen"],
	["Tracy S. Feldman"],
	["Tumovsk distr. Zonalnoe vil."],
	["Turlin_B."],
	["Tuzov"],
	["UK"],
	["Ulf Norberg"],
	["Ullasa Kodandaramaiah"],
	["V. Hula"],
	["V. Litoushik"],
	["V. Major"],
	["V. Platnev"],
	["V. Ricankova"],
	["V. Sbordoni"],
	["V. Tuzov"],
	["Van Laer"],
	["Vande Weghe"],
	["Vanek leg."],
	["Ventimiglia"],
	["Visinskas"],
	["Vladimir Lukhtanov"],
	["W. Rowe"],
	["W. ten Hagen"],
	["Walter Zelada"],
	["Welling"],
	["Wendy Harrison"],
	["Willy De Prins"],
	["Wojtusiak & Garlacz"],
	["Wolfgang Eckweiler"],
	["Wu Zhi Shan leg."],
	["www.rusinsects.com"],
	["Y. Berezhnoi"],
	["Y. Gareca"],
	["Y. Nishinaka"],
	["Yakovlev"],
	["Yi-Hsin Lee"],
	["Yuri Marusik"],
	["Yury Shevnin"],
	["Z. Fric"],
	["Z. Kolev"],
	["Z. Marcek leg."],
	["Zdenek Fric"],
	["Zdravko Kolev"],
	["Zhi"],
	["Zurlina"],
]
