#!/usr/bin/env bash

APP_NAME="voseq"

DEFAULT_DOCKER_PROJECT_NAME="${APP_NAME//_/}"
DEFAULT_DOCKER_PROJECT_NAME="${DEFAULT_DOCKER_PROJECT_NAME//-/}"
DOCKER_PROJECT_NAME="${DOCKER_PROJECT_NAME:-$DEFAULT_DOCKER_PROJECT_NAME}"

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
EXTERNAL_PORT_ADD="1"
# shellcheck disable=SC2034
POSTGRES_CONTAINER="postgres:12.2"

# TODO: we should set the compose files semi-automatically somehow
# detect if COMPOSE_OPTS declared already, otherwise use default
DEFAULT_COMPOSE_OPTS=(-f docker-compose.yml)
COMPOSE_OPTS=("${COMPOSE_OPTS[@]:-${DEFAULT_COMPOSE_OPTS[@]}}" --project-name="${DOCKER_PROJECT_NAME}")

echo "COMPOSE_OPTS: ${COMPOSE_OPTS[*]}"
