# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-31 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import public_interface.models


class Migration(migrations.Migration):

    dependencies = [
        ('public_interface', '0005_convert_genetype_to_enum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genes',
            name='gene_type',
            field=models.IntegerField(choices=[(0, 'unknown'), (1, 'mitochondrial'), (2, 'nuclear'), (3, 'ribosomal')], default=public_interface.models.GeneType(0)),
        ),
    ]
