# Generated by Django 2.2.13 on 2020-07-04 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_interface', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sequences',
            old_name='code',
            new_name='voucher',
        ),
    ]
