# Generated by Django 2.2.13 on 2020-11-22 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public_interface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequences',
            name='gene',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='public_interface.Genes'),
        ),
        migrations.AlterField(
            model_name='genes',
            name='gene_code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
