# Generated by Django 2.2.13 on 2020-11-22 07:57

from django.db import migrations

from public_interface.models import Sequences, Genes


def create_gene_codes(apps, schema_editor):
    seq_total_count = Sequences.objects.all().count()

    count = 0
    for seq in Sequences.objects.all():
        count += 1
        print(f'processing seq number {count} / {seq_total_count}')

        gene_code_str = seq.gene_code
        gene_object = Genes.objects.filter(gene_code=gene_code_str).first()
        if not gene_object:
            print(f'created gene {gene_code_str}')
            gene_object = Genes.objects.create(gene_code=gene_code_str)

        seq.gene = gene_object
        seq.save()


class Migration(migrations.Migration):

    dependencies = [
        ('public_interface', '0002_auto_20201122_0756'),
    ]

    operations = [
        migrations.RunPython(
            create_gene_codes
        ),
    ]
