# Generated by Django 2.2.13 on 2020-11-23 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_interface', '0003_auto_20201122_0757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sequences',
            name='gene_code',
        ),
    ]
