# Generated by Django 2.2.13 on 2021-03-13 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_interface', '0004_remove_sequences_gene_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flickrimages',
            name='image_file',
            field=models.ImageField(blank=True, help_text='Upload a photo from your computer so we can send it to Flickr. ', upload_to=''),
        ),
        migrations.AlterField(
            model_name='flickrimages',
            name='voucher_image',
            field=models.URLField(blank=True, help_text='Paste the URL of any Flicker image. Eg: https://www.flickr.com/photos/nsg_db/50905900296'),
        ),
    ]
